### ISSUE TITLE
Date format

### ISSUE THREAD

**Issue by 809825706** [jsonreeder/vscode-org-mode#138]
#### Is possible to custom the format of insert date?

I am using vscode on PC and orglzy on Android. It is a very well work mode. while, the default format of date in orglzy  is YYYY/MM/DD just like:

![image](https://user-images.githubusercontent.com/46601791/54472634-5daaf780-4806-11e9-8d70-8b491ada385d.png)

but in vscode:

![image](https://user-images.githubusercontent.com/46601791/54472642-83380100-4806-11e9-9c0d-f1d1d34124f6.png)

this format can't be read by orglzy.

**Comment by PGilbertSchmitt** [comment]
I believe the only issue is parsing and formatting the same way it was parsed. There would have to be an overridable config that gives you control over the format, which would then be used by the formatter. Seems like a fairly simple add, I can look into it.

**Comment by 809825706** [comment]
> I believe the only issue is parsing and formatting the same way it was parsed. There would have to be an overridable config that gives you control over the format, which would then be used by the formatter. Seems like a fairly simple add, I can look into it.

Have you fixed this problem？

**Comment by atbest** [comment]
You can modify the Regex for `timestamp` in `org.tmLanguage.json`
```json
        "timestamp": {
            "patterns": [
                {
                    "name": "variable.org",
                    "match": "[\\[<]\\d{4}-\\d{1,2}-\\d{1,2}(?:\\s+\\w{,3})?(?:\\s+\\d{1,2}\\b(:\\d{0,2})?)?\\s*[\\]>]"
                }
            ]
        }
```

**Comment by 809825706** [comment]
> You can modify the Regex for `timestamp` in `org.tmLanguage.json`
> 
> ```json
>         "timestamp": {
>             "patterns": [
>                 {
>                     "name": "variable.org",
>                     "match": "[\\[<]\\d{4}-\\d{1,2}-\\d{1,2}(?:\\s+\\w{,3})?(?:\\s+\\d{1,2}\\b(:\\d{0,2})?)?\\s*[\\]>]"
>                 }
>             ]
>         }
> ```

I tried, but it didn't work......

**Comment by stevesimmons** [comment]
If that is a regex, it will only be used for reading dates, not writing them!

Can the format for writing dates be changed to yyyy-mm-dd, so that the month and day come out with leading zeros? Dates like 2019-05-15 sort in chronological order while one like 2019-5-15 will get scrambled.

**Comment by stevesimmons** [comment]
I'll answer my own comment.... from looking at src/utils.ts, dates will appear like 2019-05-15 if you put `"org.addLeftZero": true` in `settings.json`:

**Comment by 809825706** [comment]
> I'll answer my own comment.... from looking at src/utils.ts, dates will appear like 2019-05-15 if you put `"org.addLeftZero": true` in `settings.json`:

thank you! it works!

**Comment by StefanBertels** [comment]
Hi, just found this, helped me.

AFAIK leading zeros (as in 2022-08-02) is common ([ISO 8601](https://en.wikipedia.org/wiki/ISO_8601)) and used this way in different [countries ](https://en.wikipedia.org/wiki/Date_format_by_country) and software.

While reading zero-less numbers might be a [good thing](https://en.wikipedia.org/wiki/Robustness_principle) and might be covered by ISO 8601 (which allows a lot of variants) it is used rarely IMHO.
