### ISSUE TITLE
Support of "Babel" feature?

### ISSUE THREAD

**Issue by Nordes** [jsonreeder/vscode-org-mode#142]
Hi, would you happen to know if the support of "Babel" is in the pipeline for future release?

**Comment by sipi** [comment]
currently not, we have no enough man-power but can you explain your feature request?

**Comment by Thaodan** [comment]
I think he means the whole babel feature like running src block and pasting the result into the source document during export.

**Comment by sipi** [comment]
no response to the request for clarification

**Comment by Thaodan** [comment]
I explained it, if you need more read this:
https://orgmode.org/worg/org-contrib/babel/intro.html

**Comment by sipi** [comment]
Do You want this feature ?
If yes, the only simple way to implement it (that I see) is to call Emacs in background process…
If you are interested by, I have something that does that...

**Comment by Thaodan** [comment]
Personally not as I don't use vscode. I just want more org-mode adaption and contributed with the info I have.

**Comment by sipi** [comment]
Thanks for your contribution.
I closed this issue because the original author didn't take the time to clarify his own need. Moreover, the original issue was "if the support of Babel is in the pipeline for future release?", the answer is no.
