### ISSUE TITLE
Where can I found the keybindings?

### ISSUE THREAD

**Issue by chrisoswald** [jsonreeder/vscode-org-mode#152]
I'm missing a list of the used keybindings in the documentation. For example there is shown that you can toggle the TODO-State. But nowhere is described how I can do it?

**Comment by ZoisK** [comment]
by default it's Alt-left / Alt-right.
documentation in the wiki section on TODO-items: 
https://github.com/vscode-org-mode/vscode-org-mode/wiki/TODO-Items

**Comment by sipi** [comment]
You also can find keybindings in VSCode
```File > Preferences > Keyboard Shortcuts```
then search the ```org: ``` prefix, so you will get all vscode-org-mode keybindings.
