### ISSUE TITLE
Template autocompletion

### ISSUE THREAD

**Issue by amelio-vazquez-reina** [jsonreeder/vscode-org-mode#155]
First of all - thanks for this extension! I think it will help bring more Emacs users to vscode, which I would help us accelerate the vscode community.

I am opening this issue because I noticed the following cool feature in the extension - If I start typing `ti`, it offers the `title` template, and if I press `enter`, it populates it and allows me to directly enter the `TITLE` (see screenshot below)
![Screen Shot 2019-10-14 at 11 32 01 AM](https://user-images.githubusercontent.com/1993919/66763696-50c2b500-ee76-11e9-8025-dae0eef5e4cd.png)

How does that work? Is this a `vscode-org-mode`-specific feature? 

Most critically perhaps - **Where** can I find what other such templates it auto-completes? I couldn't find them in the documentation so I'm worried I'm missing other features like this one in the extensions.

**Comment by sipi** [comment]
Hi @amelio-vazquez-reina,
it's not well documented but it uses the vscode snippet mechanism. You can found all snippets provided by vscode-org-mode extension here : https://github.com/vscode-org-mode/vscode-org-mode/blob/develop/snippets/org.json

We should add a "provided snippets" page to the wiki : https://github.com/vscode-org-mode/vscode-org-mode/wiki
