### ISSUE TITLE
What templates are supported?

### ISSUE THREAD

**Issue by amelio-vazquez-reina** [jsonreeder/vscode-org-mode#156]
I noticed this extension supports [easy templates](https://www.gnu.org/software/emacs/manual/html_node/org/Easy-templates.html), which is awesome. E.g. if I press `<` `s` `TAB`, the extension creates the `SRC` templates, just as Emacs does.. Interestingly, I didn't this feature documented in the `README.md` file (apologies if there is a better place with this info).

This makes me wonder, where can I find the full list of features / commands that the extension supports?

**Comment by sipi** [comment]
see #155 for more information about the "template" mechanism used by vscode-org-mode.
For "full" list of features / commands, please refer to (and eventually complete) the wiki https://github.com/vscode-org-mode/vscode-org-mode/wiki
