### ISSUE TITLE
Is this project still active?

### ISSUE THREAD

**Issue by sstent** [jsonreeder/vscode-org-mode#162]

**Comment by sipi** [comment]
There are still people there but not very active on this project currently. But we try to keep it alive !

**Comment by titaniumbones** [comment]
I'd love to help a little (only have a tiny amount of time!). Mainly I want my students to be able to read READM.org files in a rendered preview a la github  :-)

**Comment by sipi** [comment]
@titaniumbones **Gitlab** now supports Org files !
