### ISSUE TITLE
Can't find extension in the marketplace on Arch Linux?

### ISSUE THREAD

**Issue by idanski** [jsonreeder/vscode-org-mode#179]
Hey. 

I run vscode 1.52.1 on an Arch Linux machine and can't find the extension in the marketplace.

A friend was able to find it on his mac.

I tried both using free text search 'org mode'
and using `ext install vscode-org-mode.org-mode` both didn't find it.

This is what I see when I use the ext install.. 
![Screenshot_20210120_124209](https://user-images.githubusercontent.com/7109652/105163735-f60a1580-5b1c-11eb-964a-8df2dc2f6c21.png)

Please advise

**Comment by tamuratak** [comment]
See https://github.com/microsoft/vscode/issues/107997#issuecomment-703245178

**Comment by idanski** [comment]
I see. Thanks @tamuratak !
I installed the `visual-studio-code-bin` and it actually works now.

I'm closing this issue as I've found a workaround, but the maintainers of this extension may consider adding this extension to VSX.
