### ISSUE TITLE
Codium support?

### ISSUE THREAD

**Issue by liar666** [jsonreeder/vscode-org-mode#201]
Hi,

A few months ago I asked if it is normal that I cannot find this extension in the "market place" for Codium:
https://gitter.im/vscode-org-mode/Lobby
As there is no one that seems able to answer there, I'm creating this message to ask it again here.

Is it possible / How can I install this extension on Codium? If not, what is the technical limitation?

**Comment by liar666** [comment]
OK Found a solution:
- Go to download on page:
https://marketplace.visualstudio.com/items?itemName=tootone.org-mode
- Then in Codium: "install from VSIX"

**Comment by sipi** [comment]
Hi, just to give some related information : 
- https://github.com/VSCodium/vscodium/blob/master/DOCS.md#extensions-marketplace
- https://github.com/VSCodium/vscodium/blob/master/DOCS.md#how-to-use-the-vs-code-marketplace
