### ISSUE TITLE
Syntax highlighting within #+BEGIN_SRC blocks

### ISSUE THREAD

**Issue by renzmann** [jsonreeder/vscode-org-mode#209]
Is this a feature that's already supported?  When I try e.g.

```org
#+BEGIN_SRC python
def hello():
    print("Hello, world!")
#+END_SRC
```

I do not get python syntax highlighting within the `src` block, as we would in markdown.

I have some time to help contribute to this feature, if it's not already supported, though I would need guidance on where to make adjustments in the source code.

**Comment by sipi** [comment]
HI, you should have a look in https://github.com/vscode-org-mode/vscode-org-mode/tree/develop/syntaxes

**Comment by renzmann** [comment]
Thanks for pointing that out.  For anyone else who stumbles into this, there were two identical-looking options on the VSCode marketplace:

<img width="355" alt="Screen Shot 2022-11-15 at 8 53 26 AM" src="https://user-images.githubusercontent.com/32076780/201936998-1923a49f-be01-4a49-8f2a-742fb63d835d.png">

I had installed the top one, which was `v0.5.0`, whereas the bottom one is `v1.0.0`.  Upgrading to the newer one got the syntax highlighting working.
