### ISSUE TITLE
Insert heading should work on blank doc

### ISSUE THREAD

**Issue by jsonreeder** [jsonreeder/vscode-org-mode#30]
To reproduce:
1. First approach
  1. Open a new org file
  2. Try to run org.InsertHeaderRespectContent
  3. There will be an error: running the command failed
2. Second approach
  1. Open a new org file
  2. Insert a heading
  3. Try running org.InsertHeaderRespectContent on the line below
  4. There will be an error that the command failed

Expected behavior:
  - Should be able to insert a header to a blank document (first approach)
  - Should be able to insert a header to a document that only contains one header (second approach)

**Comment by ajtoo** [comment]
Fixed in pull #45
