### ISSUE TITLE
Promote subtree misses bullets

### ISSUE THREAD

**Issue by jsonreeder** [jsonreeder/vscode-org-mode#55]
When I call `Org: Promote Subtree` it does not modify all sub bullets:

![promote_subtree](https://cloud.githubusercontent.com/assets/10589114/24844295/75ba1e48-1d5e-11e7-8114-b0b524c3ff75.gif)

All sub bullets should be promoted.

**Comment by ajtoo** [comment]
Fixed in pull #56

**Comment by jsonreeder** [comment]
Issue #55 was fixed in pull #56?! Well I'll be...
