### ISSUE TITLE
Thank you for this extension, I want to know when I can use this extension well

### ISSUE THREAD

**Issue by dreamsuifeng** [jsonreeder/vscode-org-mode#6]

**Comment by PGilbertSchmitt** [comment]
We're looking to have a basic working version hosted on the Visual Studio marketplace by Sunday with limited functionality.

**Comment by jsonreeder** [comment]
@dreamsuifeng FYI the alpha version is now live: https://marketplace.visualstudio.com/items?itemName=tootone.org-mode
