### ISSUE TITLE
Regexes for formatting are not correct

### ISSUE THREAD

**Issue by rbenson** [jsonreeder/vscode-org-mode#74]
If we have  a sentence like:

     I *absolutely* love *GitHub*

Instead of being: I **absolutely** love **GitHub**, it appears as: I **absolutely  love GitHub.**

---
Also if we have `*/some text/*`, it will be **some text**, versus _**some text**_. I'll try to play with it this weekend

**Comment by rbenson** [comment]
I see this is covered in #73

**Comment by ajtoo** [comment]
Approved #73. Thanks

**Comment by rbenson** [comment]
Which version did you use?

**Comment by ajtoo** [comment]
We need to do another release. I'll see if I have time to get a few features together and release soonish

**Comment by rbenson** [comment]
sounds good. I'll gladly help if/where I can
